/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Puls1.C
**     Project   : Micro
**     Processor : MC56F8257
**     Component : PulseAccumulator
**     Version   : Component 01.183, Driver 02.03, CPU db: 3.00.231
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 2012-12-02, ¿ÀÀü 5:13
**     Abstract  :
**          Pulse accumulator counts the number of active edges at the input of its
**          channel.
**     Settings  :
**             Pulse accumulator       : TMRA0_PACNT
**
**
**         Used input pin              :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       7             |  GPIOC3_TA0_CMPA_O_RXD0
**             ----------------------------------------------------
**
**         Mode                        : Count
**
**         Initialization:
**              Pulse accumulator      : Disabled
**              Events                 : Enabled
**
**         Timer registers
**              Counter                : TMRA0_CNTR [F005]
**              Hold                   : TMRA0_HOLD [F004]
**              Run                    : TMRA0_CTRL [F006]
**              Prescaler              : TMRA0_CTRL [F006]
**
**         User handling procedure     : not specified
**
**     Contents  :
**         Enable           - byte Puls1_Enable(void);
**         Disable          - byte Puls1_Disable(void);
**         ResetCounter     - void Puls1_ResetCounter(void);
**         GetCounterValue  - void Puls1_GetCounterValue(word *Value);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE Puls1. */

#include "Puls1.h"

/*
** ===================================================================
**     Method      :  Puls1_Enable (component PulseAccumulator)
**
**     Description :
**         Enables the bean.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/
byte Puls1_Enable(void)
{
  setRegBitGroup(TMRA0_CTRL,CM,0x01);  /* Run counter */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  Puls1_Disable (component PulseAccumulator)
**
**     Description :
**         Disables the bean.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/
byte Puls1_Disable(void)
{
  setRegBitGroup(TMRA0_CTRL,CM,0);     /* Stop counter */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  Puls1_ResetCounter (component PulseAccumulator)
**
**     Description :
**         This method resets the pulse accumulator counter (sets to
**         zero).
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void Puls1_ResetCounter(void)
{
  setReg(TMRA0_CNTR,0x00);             /* Reset counter register */
}

/*
** ===================================================================
**     Method      :  Puls1_GetCounterValue (component PulseAccumulator)
**
**     Description :
**         This method returns the content of the pulse accumulator
**         counter.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Value           - Pointer to returned value. [Note:]
**                           Parameter type depends on the width of the
**                           selected counter (may be 8, 16, 32 or 64
**                           bits long). See the method prototype in the
**                           generated module.
**     Returns     : Nothing
** ===================================================================
*/
void Puls1_GetCounterValue(Puls1_TCounterValue *Value)
{
  *Value = getReg(TMRA0_CNTR);         /* Return counter value */
}

/*
** ===================================================================
**     Method      :  Puls1_Init (component PulseAccumulator)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void Puls1_Init(void)
{
  /* TMRA0_CTRL: CM=0,PCS=0,SCS=0,ONCE=0,LENGTH=0,DIR=0,Co_INIT=0,OM=0 */
  setReg(TMRA0_CTRL,0x00);             /* Set up mode */
  /* TMRA0_SCTRL: TCF=0,TCFIE=0,TOF=0,TOFIE=0,IEF=0,IEFIE=0,IPS=0,INPUT=0,CAPTURE_MODE=0,MSTR=0,EEOF=0,VAL=0,FORCE=0,OPS=0,OEN=0 */
  setReg(TMRA0_SCTRL,0x00);
  setReg(TMRA0_CNTR,0x00);             /* Reset counter register */
  setReg(TMRA0_LOAD,0x00);             /* Reset load register */
  /* TMRA0_FILT: ??=0,??=0,??=0,??=0,??=0,FILT_CNT=0,FILT_PER=0 */
  setReg(TMRA0_FILT,0x00);             /* Set up input filter register */
}

/* END Puls1. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
